### ISSUE TITLE
Update README to reflect skara mirrors

### ISSUE THREAD

**Issue by smlambert** [adoptium/mirror-scripts#23]
The README talks about the mercurial mirrors, but does not mention the shift to using github, and how that changes the Jenkins jobs.  An update to the README is needed to indicate that jobs are now using https://github.com/adoptium/mirror-scripts/blob/master/skaraMirror.sh (and if none are pulling from mercurial, then remove or archive that information).

**Comment by Emidowojo** [comment]
Hello @smlambert can I take this isssue?

**Comment by smlambert** [comment]
yes @Emidowojo - please take this issue.  👍

**Comment by Emidowojo** [comment]
Thank you @smlambert

**Comment by Emidowojo** [comment]
Hi, @smlambert I am an outreachy intern, and I'd like to know if this can be updated in the table for the first issues. Thank you

**Comment by Emidowojo** [comment]
@smlambert I have updated the README and pulled a PR, I am waiting for it to be merged.
Thank you

**Comment by Emidowojo** [comment]
Hi @smlambert this has been done by me and merged by @karianna here is the link https://github.com/adoptium/mirror-scripts/pull/25

**Comment by smlambert** [comment]
Closed via #25
