### ISSUE TITLE
jdk8u mirrors failing

### ISSUE THREAD

**Issue by sxa** [adoptium/mirror-scripts#43]
See https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/git-mirrors/job/adoptium/

https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/git-mirrors/job/adoptium/job/git-skara-jdk8u/ has not succeeeded for 16 days and neither has the alpine mirror at https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/git-mirrors/job/adoptium/job/git-skara-alpine-jdk8/

The aarch32 one has not run successfully for 9 days: https://ci.adoptium.net/view/Failing%20Temurin%20jobs/job/git-mirrors/job/adoptium/job/git-skara-aarch32-jdk8u/

**Comment by gdams** [comment]
Look okay now - closing
