### ISSUE TITLE
Request for mirroring jdk11u into jdk11u-fast-startup-incubator

### ISSUE THREAD

**Issue by tellison** [adoptium/mirror-scripts#6]
The Adoptium Incubator project is hosting some new work based upon OpenJDK 11u.

As such, we would like a mirror of the upstream OpenJDK 11u into the Master branch of the [jdk11u-fast-startup-incubator](https://github.com/adoptium/jdk11u-fast-startup-incubator) repository.  This will be an unmodified copy of the upstream code in the same way we do today for [AdoptOpenJDK's mirror](https://github.com/AdoptOpenJDK/openjdk-jdk11u).  It will require a new Jenkins job, again matching the behavior and schedule of [the existing mirroring job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/git-hg-jdk11u/).

The incubator work will then be conducted on a new branch of the `jdk11u-fast-startup-incubator` and be occasionally rebased on the mirrored code.

**Comment by gdams** [comment]
complete
